#define PLAYER_VIEWHEIGHT 41.0

// Returns casing spawn height adjusted for crouching.
script aow_casingheight (int height)
{
	SetResultValue(FixedMul(FixedDiv(GetActorViewHeight(0), PLAYER_VIEWHEIGHT), height));
}

script aow_isopengl (void)
{
	SetResultValue(IsOpenGL());
}

script aow_bloodrevolver DEATH
{
	SetActivatorToTarget(0);
	if (CheckWeapon("BloodRevolver"))
		GiveInventory("BloodRevolverAmmo", 1);
}
