#define NUM_TEAMS 2

function str TeamName(int team)
{
	switch (team)
	{
	case TEAM_RED: return "Red";
	case TEAM_BLUE: return "Blue";
	}
	return "Unknown Team";
}

function str TeamColorCode(int team)
{
	switch (team)
	{
	case TEAM_RED: return "\cg";
	case TEAM_BLUE: return "\ch";
	}
	return "\cu";
}

function str TeamNameColored(int team)
{
	return StrParam(s:TeamColorCode(team), s:TeamName(team));
}
